### ISSUE TITLE
make_video_by_streamer seems broken

### ISSUE THREAD

**Issue by codeheroics** [pelledrijver/highlights-bot#8]
Hi! Thanks for the great project!

I’m trying to get it to run, and while I’m able to correctly run the basic example using `make_video_by_category`, I can’t run anything using the `make_video_by_streamer` method. as I always get the following error:

```
 ~ python highlight2.py
Succesfully fetched clip data
Traceback (most recent call last):
  File "highlight2.py", line 13, in <module>
    highlight_generator.make_video_by_streamer(streamers = ["Ninja", "Myth"], started_at = started_at, ended_at = ended_at)
  File "/home/code/.local/lib/python3.8/site-packages/twitch_highlights/__init__.py", line 52, in make_video_by_streamer
    clip_edit.create_video_from_json(clips, output_name, language, video_length, render_settings, sort_by, filter_copyright, acr_credentials)
  File "/home/code/.local/lib/python3.8/site-packages/twitch_highlights/clip_edit.py", line 123, in create_video_from_json
    clips = preprocess_clips(clips, language)
  File "/home/code/.local/lib/python3.8/site-packages/twitch_highlights/clip_edit.py", line 110, in preprocess_clips
    video_url = clip["thumbnail_url"].split("-preview")[0] + ".mp4"
TypeError: list indices must be integers or slices, not str
```

I’d be glad to give additional data if necessary to debug! :)

**Comment by rsmithtamu** [comment]
Hello,
I am seeing the same error.  

`$ C:/Users/rsmit/AppData/Local/Programs/Python/Python39/python.exe c:/Users/rsmit/Documents/GitHub/Twitch-Highlights/twitchhl.py
Succesfully fetched clip data
Traceback (most recent call last):
  File "c:\Users\rsmit\Documents\GitHub\Twitch-Highlights\twitchhl.py", line 23, in <module>
    highlight_generator.make_video_by_streamer(streamers = ["Ticklefitz"])
  File "C:\Users\rsmit\AppData\Local\Programs\Python\Python39\lib\site-packages\twitch_highlights\__init__.py", line 52, in make_video_by_streamer
    clip_edit.create_video_from_json(clips, output_name, language, video_length, render_settings, sort_by, filter_copyright, acr_credentials)
  File "C:\Users\rsmit\AppData\Local\Programs\Python\Python39\lib\site-packages\twitch_highlights\clip_edit.py", line 123, in create_video_from_json
    clips = preprocess_clips(clips, language)
  File "C:\Users\rsmit\AppData\Local\Programs\Python\Python39\lib\site-packages\twitch_highlights\clip_edit.py", line 110, in preprocess_clips
    video_url = clip["thumbnail_url"].split("-preview")[0] + ".mp4"
TypeError: list indices must be integers or slices, not str`

**Comment by pelledrijver** [comment]
Hey @codeheroics, thanks for reporting the problem! There seems a tiny bug in the code where I merge the lists containing clip metadata of each streamer into one big list. (Rooky mistake! Forgot to flatten the list...). I'll release a new version of the package next week in which the problem is patched!

**Comment by codeheroics** [comment]
Seeing this, I realize now that I had meant, but forgotten to, answer to your post a few months ago… So better late than never: Thank you so much for tackling and fixing this :)
